cd win32-3139
gcj -v -C -g0 -fsource=1.4 -d ../../bin \
org/eclipse/swt/custom/StyledText.java \
org/eclipse/swt/custom/StyledTextContent.java \
org/eclipse/swt/custom/StyleRange.java \
org/eclipse/swt/custom/TextChangedEvent.java \
org/eclipse/swt/custom/TextChangeListener.java \
org/eclipse/swt/custom/TextChangingEvent.java \
org/eclipse/swt/custom/VerifyKeyListener.java \
org/eclipse/swt/dnd/ByteArrayTransfer.java \
org/eclipse/swt/dnd/Clipboard.java \
org/eclipse/swt/dnd/DND.java \
org/eclipse/swt/dnd/DropTarget.java \
org/eclipse/swt/dnd/DropTargetAdapter.java \
org/eclipse/swt/dnd/DropTargetEvent.java \
org/eclipse/swt/dnd/FileTransfer.java \
org/eclipse/swt/dnd/TextTransfer.java \
org/eclipse/swt/dnd/Transfer.java \
org/eclipse/swt/dnd/TransferData.java \
org/eclipse/swt/events/ControlAdapter.java \
org/eclipse/swt/events/ControlEvent.java \
org/eclipse/swt/events/DisposeEvent.java \
org/eclipse/swt/events/DisposeListener.java \
org/eclipse/swt/events/FocusAdapter.java \
org/eclipse/swt/events/FocusEvent.java \
org/eclipse/swt/events/FocusListener.java \
org/eclipse/swt/events/KeyAdapter.java \
org/eclipse/swt/events/KeyEvent.java \
org/eclipse/swt/events/KeyListener.java \
org/eclipse/swt/events/MenuAdapter.java \
org/eclipse/swt/events/MenuEvent.java \
org/eclipse/swt/events/ModifyEvent.java \
org/eclipse/swt/events/ModifyListener.java \
org/eclipse/swt/events/MouseAdapter.java \
org/eclipse/swt/events/MouseEvent.java \
org/eclipse/swt/events/PaintEvent.java \
org/eclipse/swt/events/PaintListener.java \
org/eclipse/swt/events/SelectionAdapter.java \
org/eclipse/swt/events/SelectionEvent.java \
org/eclipse/swt/events/SelectionListener.java \
org/eclipse/swt/events/ShellAdapter.java \
org/eclipse/swt/events/TraverseEvent.java \
org/eclipse/swt/events/TraverseListener.java \
org/eclipse/swt/events/VerifyEvent.java \
org/eclipse/swt/events/VerifyListener.java \
org/eclipse/swt/graphics/Color.java \
org/eclipse/swt/graphics/Font.java \
org/eclipse/swt/graphics/FontData.java \
org/eclipse/swt/graphics/FontMetrics.java \
org/eclipse/swt/graphics/GC.java \
org/eclipse/swt/graphics/Image.java \
org/eclipse/swt/graphics/Point.java \
org/eclipse/swt/graphics/Rectangle.java \
org/eclipse/swt/internal/image/PNGFileFormat.java \
org/eclipse/swt/layout/FillLayout.java \
org/eclipse/swt/layout/FormAttachment.java \
org/eclipse/swt/layout/FormData.java \
org/eclipse/swt/layout/FormLayout.java \
org/eclipse/swt/layout/GridData.java \
org/eclipse/swt/layout/GridLayout.java \
org/eclipse/swt/layout/RowLayout.java \
org/eclipse/swt/program/Program.java \
org/eclipse/swt/SWT.java \
org/eclipse/swt/widgets/Button.java \
org/eclipse/swt/widgets/Caret.java \
org/eclipse/swt/widgets/Combo.java \
org/eclipse/swt/widgets/Composite.java \
org/eclipse/swt/widgets/Control.java \
org/eclipse/swt/widgets/Dialog.java \
org/eclipse/swt/widgets/Display.java \
org/eclipse/swt/widgets/Event.java \
org/eclipse/swt/widgets/FileDialog.java \
org/eclipse/swt/widgets/Group.java \
org/eclipse/swt/widgets/Label.java \
org/eclipse/swt/widgets/List.java \
org/eclipse/swt/widgets/Listener.java \
org/eclipse/swt/widgets/Menu.java \
org/eclipse/swt/widgets/MenuItem.java \
org/eclipse/swt/widgets/MessageBox.java \
org/eclipse/swt/widgets/ProgressBar.java \
org/eclipse/swt/widgets/ScrollBar.java \
org/eclipse/swt/widgets/Shell.java \
org/eclipse/swt/widgets/Text.java
